id: qiime2-dada2-denoising
name: 'Qiime2 -> Step 3: DADA2 Denoising'
description: 'This task uses DADA2 to perform donoising, error correction and other
  DADA2

  functions.


  Input data are demultiplexed sequences in "fastq" format which should have been

  imported with the first task of the Coretex Qiime pipeline (Import) or demultiplexed

  in the second (Demultiplexing sequences).


  The following will be performed by DADA2:


  Error Modeling and Quality Filtering: DADA2 begins by estimating the error rates

  of each sequencing run and filtering out low-quality reads. This is important

  because sequencing errors are common, and distinguishing true biological

  variation from sequencing errors is crucial for accurate downstream analysis.


  Read Pair Assembly: DADA2 works with paired-end sequencing data and assembles

  the forward and reverse reads into full-length sequences. This step helps

  to capture the complete biological sequences and increases accuracy.


  Error Correction: By using the estimated error rates, DADA2 identifies

  and corrects sequencing errors. Instead of clustering sequences into

  OTUs, DADA2 seeks to resolve each unique biological sequence variant

  (often referred to as amplicon sequence variants or ASVs) and their

  abundances directly from the raw data.


  Chimera Detection: DADA2 employs a statistical approach to identify

  and remove chimera sequences, which are artifacts created during

  PCR amplification. This is another critical step to ensure that

  only genuine biological sequences are retained.


  Results: The output of DADA2''s denoising process is a table

  that contains the identified sequence variants along with

  their respective abundances in each sample. This table can

  then be used for downstream analyses, such as taxonomic classification,

  diversity analysis, and more.'
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: 'A dataset which contains demultiplexed fastq sequences which

      have been imported into Qiime2.'
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: The dataset to which this TaskRun will output it's results
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: trimLeftF
    description: "Amount of bases to be trimmed from the start of the forward sequences.\r\
      \nThis value is determined based on the \"Quality Plots\" which are\r\ngenerated\
      \ by the \"Step #1\" template. The plot can be found in\r\n\"demux.qzv\" file."
    value: null
    data_type: int
    required: false
  - name: trimLeftR
    description: "Amount of bases to be trimmed from the start of the reverse sequences.\r\
      \nThis value is determined based on the \"Quality Plots\" which are\r\ngenerated\
      \ by the \"Step #1\" template. The plot can be found in\r\n\"demux.qzv\" file."
    value: null
    data_type: int
    required: false
  - name: truncLenF
    description: "(If this field is empty, the value will be determined automatically)\r\
      \nPosition at which the forward sequence will be truncated. This allows user\r\
      \nto remove low quality regions of the sequences.\r\nThis value is determined\
      \ based on the \"Quality Plots\" which are\r\ngenerated by the \"Step #1\" template.\
      \ The plot can be found in\r\n\"demux.qzv\" file."
    value: null
    data_type: int
    required: false
  - name: truncLenR
    description: "(If this field is empty, the value will be determined automatically)\r\
      \nPosition at which the reverse sequence will be truncated. This allows user\r\
      \nto remove low quality regions of the sequences.\r\nThis value is determined\
      \ based on the \"Quality Plots\" which are\r\ngenerated by the \"Step #1\" template.\
      \ The plot can be found in\r\n\"demux.qzv\" file."
    value: null
    data_type: int
    required: false
  - name: threads
    description: Number of threads to use for qiime commands. If empty, multithreading will not be used.
      Set to -1 to use a thread for each CPU core
    value: -1
    data_type: int
    required: false
