id: bio-sequence-alignment
name: Microbiome Forensics -> Sequence Alignment
description: Task template for aligning/mapping sequence reads to reference genome.
  Either genomeUrl or referenceDataset has to be filled
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Coretex dataset holding sequence reads on which alignment will be
      performed
    value: null
    data_type: dataset
    required: true
  - name: referenceDataset
    description: Coretex dataset with the reference genome (if genomeUrl is provided
      this parameter will be ignored)
    value: null
    data_type: dataset
    required: false
- name: outputs
  params:
  - name: samDataset
    description: The dataset to which the output aligned sequences will be uploaded
      in the SAM format
    value: null
    data_type: dataset
    required: false
  - name: bamDataset
    description: The dataset to which the output aligned sequences, converted to binary,
      will be uploaded in the BAM format
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: genomeUrl
    description: 'URL to the reference genome. The URL should lead directly to the
      file (e.g. .../hg38.fa.gz)

      and be in either gz format or uncompressed'
    value: null
    data_type: str
    required: false
  - name: convertToBAM
    description: Setting this to true will generate an additional coretex dataset
      with the output files in BAM format
    value: true
    data_type: bool
    required: true
