id: qiime2-otu-clustering
name: 'Qiime2 -> Step 4: OTU Clustering'
description: 'This task uses vsearch to perform OTU clustering with the de novo method.


  OTU stands for "Operational Taxonomic Unit." OTU clustering involves grouping

  similar DNA or RNA sequences together based on a predefined sequence similarity

  threshold. The similarity threshold is typically set at a certain percentage (e.g.,
  97%)

  of sequence identity. Sequences that share this level of

  similarity are grouped into the same OTU.


  The input is the dataset created by the third task in the Coretex Qiime Pipeline,

  DADA2. What gets used for the clustering is the feature table.


  The output is a BIOM file with OTUs.'
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: 'A dataset which contains a featrue table generated in the third
      task form

      the Coretex Qiime pipeline, DADA2.'
    value: null
    data_type: dataset
    required: true
  - name: referenceDataset
    description: 'A dataset that contains a single sample with the reference sequences
      either

      in a single .fasta file, or imported in a .qza file. If the file is in fasta

      it will be imported to .qza and upoaded as a cache to Coretex'
    value: null
    data_type: dataset
    required: false
- name: outputs
  params:
  - name: outputDataset
    description: The dataset to which this TaskRun will output it's results
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: clusteringMethod
    description: "This parameter decides which method will be used for OTU clustering.\n\
      Available methods are:\n    - De Novo\n    - Closed Reference\n    - Open Reference"
    value:
      selected: 0
      options:
      - De Novo
      - Closed Reference
      - Open Reference
    data_type: enum
    required: true
  - name: percentIdentity
    description: 'In OTU clustering, sequences that share a certain level of sequence
      identity are

      considered to be part of the same taxonomic unit. This similarity threshold,

      often expressed as a percentage, determines how closely related sequences need

      to be in order to be grouped together. For example, if the percent identity

      threshold is set at 97%, it means that sequences with at least 97% identical

      bases are clustered into the same OTU.'
    value: 0.99
    data_type: float
    required: true
  - name: threads
    description: Number of threads to use for qiime commands. If empty, multithreading will not be used.
      Set to -1 to use a thread for each CPU core
    value: -1
    data_type: int
    required: false
