id: phyloseq-full-workflow
name: Phyloseq -> Full Workflow
description: Workflow for cleaning the data using DADA2 and generating phylogenetic
  tree based on the cleaned data then running Alpha & Beta diversity analyses.
project_type: 11
is_active: true
jobs:
  step-1-dada2-denoising:
    template_id: phyloseq-step-1-dada2-denoising

  step-2-compare-dada2-results:
    template_id: phyloseq-compare-dada-2-results
    param_groups:
      inputs:
        dada2Artifacts: step-1-dada2-denoising.artifacts

  step-3-generate-phylogenetic-tree:
    template_id: phyloseq-step-2-phylogenetic-tree
    param_groups:
      inputs:
        dada2Artifacts: step-2-compare-dada2-results.artifacts

  step-4-alpha-and-beta-diversity-analysis:
    template_id: phyloseq-alpha-beta-diversity-analysis
    param_groups:
      inputs:
        dataset: step-3-generate-phylogenetic-tree.outputDataset
