id: qiime2-taxonomic-analysis
name: 'Qiime2 -> Step 5: Taxonomic Analysis'
description: "Taxonomic analysis is used to extract taxonomy (taxonomic composition)\
  \ of\nthe samples. It achieves this by using a ML model for this process.\n\nThe\
  \ info that gets extracted is also visualized, so you\ncan easily explore multiple\
  \ levels of taxonomic composition of the samples.\n\nInput data is:\n    - File\
  \ which contains metadata about samples\n    - ML model which predicts taxonomic\
  \ composition of a\n      given sequence\n    - Filtered sequence data generated\
  \ by the third task in the Coretex\n      Qiime pipeline, DADA2\n\nOutput data is\
  \ the taxonomic composition of the provided samples."
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: "A dataset which contains denoised fastq sequences. This\r\ndataset\
      \ is output of the \"Step #3\" template. Dataset is generated\r\nby Qiime2 tool."
    value: null
    data_type: dataset
    required: true
  - name: importedDataset
    description: "A dataset which contains demultiplexed fastq sequences. This\r\n\
      dataset is output of the \"Step #2\" template. Dataset is generated\r\nby Qiime2\
      \ tool."
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: The dataset to which this TaskRun will output it's results
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: classifier
    description: "Classifier which will be used to perform taxonomic analysis\r\n\
      on the provided data."
    value: '{RESOURCES_SERVER_URL}/experiments/gg-13-8-99-515-806-nb-classifier.qza'
    data_type: str
    required: true
  - name: threads
    description: Number of threads to use for qiime commands. If empty, multithreading will not be used.
      Set to -1 to use a thread for each CPU core
    value: -1
    data_type: int
    required: false
